# Generated by Django 5.1.7 on 2025-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_book_app', '0003_readingcomment_readingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='book_status',
            field=models.IntegerField(choices=[(0, '絵本持っている'), (1, '図書館等で借りた')], default=0),
        ),
    ]
