# Generated by Django 5.1.7 on 2025-04-15 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('picture_book_app', '0005_book_family_id_readingrecord_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='accounts.family'),
        ),
    ]
