# Generated by Django 5.1.7 on 2025-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('publisher', models.CharField(max_length=225)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
