# Generated by Django 5.1.7 on 2025-04-07 04:41

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('picture_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.family', null=False),
        ),
    ]
