# Generated by Django 5.1.7 on 2025-04-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='family',
            new_name='family_id',
        ),
    ]
