# Generated by Django 5.1.7 on 2025-04-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_book_app', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('read_count', models.PositiveIntegerField()),
                ('book_status', models.IntegerField(choices=[(0, '絵本持っている'), (1, '図書館等で借りた')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reading_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reading_videos/')),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='picture_book_app.book')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='picture_book_app.child')),
                ('reading_comments', models.ManyToManyField(blank=True, to='picture_book_app.readingcomment')),
            ],
        ),
    ]
