# Generated by Django 5.1.7 on 2025-04-15 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('picture_book_app', '0004_alter_readingrecord_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.family'),
        ),
        migrations.AddField(
            model_name='readingrecord',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='book_status',
            field=models.IntegerField(choices=[(0, '持ってる'), (1, '借りた')], default=0),
        ),
    ]
