# Generated by Django 5.1.7 on 2025-04-02 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family_invitations', to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.family'),
            preserve_default=False,
        ),
    ]
