# Generated by Django 5.1.7 on 2025-04-02 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_family_id_alter_invitation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
