# Generated by Django 5.1.7 on 2025-03-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_family_child_user_family_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
